// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/28/2025, 11:29:39 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/coding/shadcn-test-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/plugins/**/*.{js,ts,mjs}","C:/coding/shadcn-test-2/composables/**/*.{js,ts,mjs}","C:/coding/shadcn-test-2/utils/**/*.{js,ts,mjs}","C:/coding/shadcn-test-2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/coding/shadcn-test-2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;